<?php 

/**
 * ProcessWire General site settings module
 *
 * Allows to set global site settings 
 *
 * by Piotr Markiewicz (pmarki)
 * 
 * Additional revisions by Marc Wolf (@macrura)
 *
 * https://processwire.com
 *
 * http://modules.processwire.com/modules/process-general-settings/
 * https://github.com/flydev-fr/ProcessGeneralSettings
 * 
 */

class GeneralSettings extends Process implements Module, ConfigurableModule {

	public static function getModuleInfo() {
		return array(
			'title' 	=> __('General Site Settings', __FILE__),
			'summary' 	=> __('Configurable module that stores a variety of global site settings', __FILE__),
			'version' 	=> 122,
			'permanent' => false, 
			'autoload' 	=> true,
			'icon' 		=> 'sliders', 
			//'installs'	=> 'ProcessGeneralSettings',
			'requires' 	=> 'ProcessGeneralSettings',
			);
	}

	protected static $defaults = array(
			'global' => 'g_settings',
			'settings' => '{"0":{"api":"title","label":"Your site title","type":"Text","width":"100","description":"","select":""}}',
			'settings_import' => '',
	);


	public function init() {

		parent::init();

		if ($this->wire('user')->isLoggedin() && $this->input->get('name') == __CLASS__) {
			$root = $this->config->urls->siteModules . 'ProcessGeneralSettings'; // parent module – this should be adjusted
			$this->config->styles->prepend($root . '/' . 'Settings.css');
			$this->config->scripts->add($root . '/' . 'Settings.js');
		}

		//register wire 'global'
		if (isset($this->data['global'])) {
			$this->wire($this->data['global'], $this);
		}

		if (!isset($this->data['settings'])) {
			parent::init();
			return;
		}

		//set api as key with value as value
		//it makes it callable $settings->key
		$langData = array();
		$data = json_decode($this->data['settings'], true);
		foreach ($data as $key => $field) {
			if (!isset($field['api'])) continue;

			$value = (isset($field['value']) ? $field['value'] : '');
			if ($field['type'] == 'Textarea') {
				$value = nl2br($value);
			}

			if ($this->user->language) {
				//if api ends with language name: site_name_polish, add its value to langData array
				//so if user language is polish calling site_name will return its polish value
				if (strpos($field['api'], '_'.$this->user->language->name) !== false) {
					//$api without language suffix - site_title
					$api = str_replace('_'.$this->user->language->name, '', $field['api']);
					foreach ($data as $k => $f) {
						if ($f['api'] === $api) {
							$langData[$api] = $field['value'];
						}
					}
				}
			}
			$this->set($field['api'], $value);
		}
		foreach ($langData as $key => $value) {
			$this->set($key, $value);
		}

	}


	/**
	 * Render all settings with basic markup
	 * 
	 * @return string markup
	 *
	 */
	public function render() {
		$out = '<p>';
		foreach (json_decode($this->data['settings'], true) as $key => $field) {
			if (isset($field['api']) && $field['type'] != 'Fieldset') {
				$v = (isset($field['value'])) ? $field['value'] : '';
				$out .= $this->wire('sanitizer')->entities($field['label'])
					. ' ('. $field['api'] . ') => ' 
					. nl2br($this->wire('sanitizer')->entities($v)) . '<br>';
			}
		}
		return $out .'</p>';
	}


	static public function getModuleConfigInputfields(array $data) {
		$data = array_merge(self::$defaults, $data);
		$tableRows = '';
		$json = (isset( $data['settings'] )) ? json_decode($data['settings'], true) : array();

		if(isset($data['settings_import']) && $data['settings_import'] != '') {
			$json = json_decode($data['settings_import'], true);
			$data['settings'] = $data['settings_import'];
			$data['settings_import'] = '';
		}

		if(!is_array($json)) $json = array();

		$sanitizer = wire('sanitizer');
		foreach ($json as $key => $value) {
			$api = isset($value['api']) ? $sanitizer->entities($value['api']) : '';
			$label = isset($value['label']) ? $sanitizer->entities($value['label']) : '';
			$type = isset($value['type']) ? $sanitizer->entities($value['type']) : '';
			$width = isset($value['width']) ? $sanitizer->entities($value['width']) : '';
			$required = !empty($value['required']) ? 'True' : 'False';
			$tableRows .= "<tr data-index='{$key}'>"
				. "<td class='pgs-drag'><i class='fa fa-bars' aria-hidden='true'></i></td>"
				. "<td>{$label}</td>"
				. "<td>{$api}</td>"
				. "<td>{$type}</td>"
				. "<td>{$width}%</td>"
				. "<td>{$required}</td>"
				. "<td class='pgs-actions'><a class='edit uk-button uk-button-default uk-button-small' href='#'><i class='fa fa-pencil' aria-hidden='true'></i></a> <a class='delete uk-button uk-button-danger uk-button-small' href='#'><i class='fa fa-trash' aria-hidden='true'></i></a></td>"
				. "</tr>";
		}

		$fields = new InputfieldWrapper();
		$modules = wire('modules');

		//------------------------------------------
		$field = $modules->get("InputfieldMarkup");
		$field->label = __("Help", __FILE__);
		$help = ('<b>API variable</b> - Any combination of letters (a-z), numbers (0-9) and underscores (no spaces). 
				You can call it in template files to output a value ($settings->site_name will return "My site").
				<br>IMPORTANT: take care to not overload ProcessWire properties ($page, $user, etc.). It must be unique across all settings.<br>
				<b>Label</b> - descriptive name for a backend user<br>
				<b>Required</b> - True = required field, False = optional field<br>
				<b>Description</b> - longer explanation shown as notes in ProcessWire backend<br>
				<b>Width</b> - field width in %, set between 10 and 100<br>
				<b>Options for select or radios</b> - this will be used as names and labels, the best one word only');
		$field->entityEncodeText = false;
		$field->entityEncodeLabel = false;
		$field->attr('value', $help); 
		$field->collapsed = Inputfield::collapsedYes;
		$fields->append($field);

		//------------------------------------------
		$field = $modules->get("InputfieldText");
		$field->attr('name', 'global');
		$field->label = __("Global name", __FILE__);
		$field->attr('value', $data['global']); 
		$field->description = __('Use to call settings property in frontend ($settings->property).', __FILE__);
		$field->notes = __("After changing make sure to change it in your template files.", __FILE__);
		$field->collapsed = Inputfield::collapsedYes;
		$fields->append($field);

		//------------------------------------------
		$field = wire('modules')->get("InputfieldTextarea");
		$field->attr('name', 'settings');
		$field->attr('id', 'settings');
		$field->label = __("Json data", __FILE__);
		$field->attr('value', $data['settings']); 
		$field->columnWidth = 34;
		$field->collapsed = Inputfield::collapsedYes;
		$fields->append($field);


		//------------------------------------------
		$field = wire('modules')->get("InputfieldTextarea");
		$field->attr('name', 'settings_import');
		$field->attr('id', 'settings_import');
		$field->label = __("Import Settings Config", __FILE__);
		$field->description = __('Paste a JSON array of settings here - Warning - pasting here will clear all saved settings in the Process Module.', __FILE__);
		$field->attr('value', $data['settings_import'] ?? ''); 
		$field->collapsed = Inputfield::collapsedYes;
		$fields->append($field);


		//------------------------------------------
		$field = $modules->get('InputfieldMarkup');
		$field->attr('name', 'settings_table');
		$field->label = __("Settings", __FILE__);
		$field->value = "<div id='pgsSettingsTableWrap'>"
			. "<table id='pgsSettingsTable' class='uk-table uk-table-divider uk-table-small'>"
			. "<thead><tr><th></th><th>Label</th><th>API</th><th>Type</th><th>Width</th><th>Required</th><th class='pgs-actions'>Actions</th></tr></thead>"
			. "<tbody>{$tableRows}</tbody>"
			. "</table>"
			. "<a id='addNew' href='#' class='uk-button uk-button-primary uk-button-small'><i class='fa fa-plus-circle' aria-hidden='true'></i> Add field</a>"
			. "</div>";
		$fields->append($field);


		return $fields;
	}


}
